/*
Copyright (C) DocuSign, Inc.  All rights reserved.

This source code is intended only as a supplement to DocuSign SDK and/or on-line documentation.

This sample is designed to demonstrate DocuSign features and is not intended for production use.
Code and policy for a production application must be developed to meet the specific data and
security requirements of the application.

THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
FITNESS FOR A PARTICULAR PURPOSE.
 */

package net.docusign.credential.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CredentialSoap", targetNamespace = "http://www.docusign.net/API/Credential")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CredentialSoap {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Ping", action = "http://www.docusign.net/API/Credential/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://www.docusign.net/API/Credential")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.PingResponse")
    public boolean ping();

    /**
     * 
     * @param email
     * @param password
     * @return
     *     returns net.docusign.credential.api.LoginResponse.LoginResult
     */
    @WebMethod(operationName = "Login", action = "http://www.docusign.net/API/Credential/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://www.docusign.net/API/Credential")
    @RequestWrapper(localName = "Login", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.LoginResponse")
    public net.docusign.credential.api.LoginResponse.LoginResult login(
        @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/Credential")
        String email,
        @WebParam(name = "Password", targetNamespace = "http://www.docusign.net/API/Credential")
        String password);

    /**
     * 
     * @param accountID
     * @param email
     * @param goToEnvelopeID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAuthenticationToken", action = "http://www.docusign.net/API/Credential/GetAuthenticationToken")
    @WebResult(name = "GetAuthenticationTokenResult", targetNamespace = "http://www.docusign.net/API/Credential")
    @RequestWrapper(localName = "GetAuthenticationToken", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.GetAuthenticationToken")
    @ResponseWrapper(localName = "GetAuthenticationTokenResponse", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.GetAuthenticationTokenResponse")
    public String getAuthenticationToken(
        @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/Credential")
        String email,
        @WebParam(name = "Password", targetNamespace = "http://www.docusign.net/API/Credential")
        String password,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/Credential")
        String accountID,
        @WebParam(name = "GoToEnvelopeID", targetNamespace = "http://www.docusign.net/API/Credential")
        String goToEnvelopeID);

    /**
     * 
     * @param accountID
     * @param email
     * @param envelopeID
     * @param password
     * @param returnURL
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSenderToken", action = "http://www.docusign.net/API/Credential/RequestSenderToken")
    @WebResult(name = "RequestSenderTokenResult", targetNamespace = "http://www.docusign.net/API/Credential")
    @RequestWrapper(localName = "RequestSenderToken", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.RequestSenderToken")
    @ResponseWrapper(localName = "RequestSenderTokenResponse", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.RequestSenderTokenResponse")
    public String requestSenderToken(
        @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/Credential")
        String email,
        @WebParam(name = "Password", targetNamespace = "http://www.docusign.net/API/Credential")
        String password,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/Credential")
        String accountID,
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/Credential")
        String envelopeID,
        @WebParam(name = "ReturnURL", targetNamespace = "http://www.docusign.net/API/Credential")
        String returnURL);

    /**
     * 
     * @param email
     * @param suppressNavigation
     * @param envelopeID
     * @param password
     * @param returnURL
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestCorrectToken", action = "http://www.docusign.net/API/Credential/RequestCorrectToken")
    @WebResult(name = "RequestCorrectTokenResult", targetNamespace = "http://www.docusign.net/API/Credential")
    @RequestWrapper(localName = "RequestCorrectToken", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.RequestCorrectToken")
    @ResponseWrapper(localName = "RequestCorrectTokenResponse", targetNamespace = "http://www.docusign.net/API/Credential", className = "net.docusign.credential.api.RequestCorrectTokenResponse")
    public String requestCorrectToken(
        @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/Credential")
        String email,
        @WebParam(name = "Password", targetNamespace = "http://www.docusign.net/API/Credential")
        String password,
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/Credential")
        String envelopeID,
        @WebParam(name = "SuppressNavigation", targetNamespace = "http://www.docusign.net/API/Credential")
        boolean suppressNavigation,
        @WebParam(name = "ReturnURL", targetNamespace = "http://www.docusign.net/API/Credential")
        String returnURL);

}
