/*
Copyright (C) DocuSign, Inc.  All rights reserved.

This source code is intended only as a supplement to DocuSign SDK and/or on-line documentation.

This sample is designed to demonstrate DocuSign features and is not intended for production use.
Code and policy for a production application must be developed to meet the specific data and
security requirements of the application.

THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
FITNESS FOR A PARTICULAR PURPOSE.
*/

package net.docusign.ws3_0.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Sep 27 16:58:56 EEST 2010
 * Generated source version: 2.2.9
 * 
 */

public final class APIServiceSoap_APIServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.docusign.net/API/3.0", "APIService");

    private APIServiceSoap_APIServiceSoap12_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = APIService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        APIService ss = new APIService(wsdlURL, SERVICE_NAME);
        APIServiceSoap port = ss.getAPIServiceSoap12();  
        
        {
        System.out.println("Invoking requestTemplate...");
        java.lang.String _requestTemplate_templateID = "";
        boolean _requestTemplate_includeDocumentBytes = false;
        net.docusign.ws3_0.api.EnvelopeTemplate _requestTemplate__return = port.requestTemplate(_requestTemplate_templateID, _requestTemplate_includeDocumentBytes);
        System.out.println("requestTemplate.result=" + _requestTemplate__return);


        }
        {
        System.out.println("Invoking requestTemplates...");
        java.lang.String _requestTemplates_accountID = "";
        boolean _requestTemplates_includeAdvancedTemplates = false;
        net.docusign.ws3_0.api.EnvelopeTemplates _requestTemplates__return = port.requestTemplates(_requestTemplates_accountID, _requestTemplates_includeAdvancedTemplates);
        System.out.println("requestTemplates.result=" + _requestTemplates__return);


        }
        {
        System.out.println("Invoking requestRecipientToken...");
        java.lang.String _requestRecipientToken_envelopeID = "";
        java.lang.String _requestRecipientToken_clientUserID = "";
        java.lang.String _requestRecipientToken_username = "";
        java.lang.String _requestRecipientToken_email = "";
        net.docusign.ws3_0.api.RequestRecipientTokenAuthenticationAssertion _requestRecipientToken_authenticationAssertion = null;
        net.docusign.ws3_0.api.RequestRecipientTokenClientURLs _requestRecipientToken_clientURLs = null;
        java.lang.String _requestRecipientToken__return = port.requestRecipientToken(_requestRecipientToken_envelopeID, _requestRecipientToken_clientUserID, _requestRecipientToken_username, _requestRecipientToken_email, _requestRecipientToken_authenticationAssertion, _requestRecipientToken_clientURLs);
        System.out.println("requestRecipientToken.result=" + _requestRecipientToken__return);


        }
        {
        System.out.println("Invoking requestDocumentPDFs...");
        java.lang.String _requestDocumentPDFs_envelopeID = "";
        net.docusign.ws3_0.api.DocumentPDFs _requestDocumentPDFs__return = port.requestDocumentPDFs(_requestDocumentPDFs_envelopeID);
        System.out.println("requestDocumentPDFs.result=" + _requestDocumentPDFs__return);


        }
        {
        System.out.println("Invoking createEnvelopeFromTemplatesAndForms...");
        net.docusign.ws3_0.api.EnvelopeInformation _createEnvelopeFromTemplatesAndForms_envelopeInformation = null;
        net.docusign.ws3_0.api.ArrayOfCompositeTemplate _createEnvelopeFromTemplatesAndForms_compositeTemplates = null;
        boolean _createEnvelopeFromTemplatesAndForms_activateEnvelope = false;
        net.docusign.ws3_0.api.EnvelopeStatus _createEnvelopeFromTemplatesAndForms__return = port.createEnvelopeFromTemplatesAndForms(_createEnvelopeFromTemplatesAndForms_envelopeInformation, _createEnvelopeFromTemplatesAndForms_compositeTemplates, _createEnvelopeFromTemplatesAndForms_activateEnvelope);
        System.out.println("createEnvelopeFromTemplatesAndForms.result=" + _createEnvelopeFromTemplatesAndForms__return);


        }
        {
        System.out.println("Invoking requestPDF...");
        java.lang.String _requestPDF_envelopeID = "";
        net.docusign.ws3_0.api.EnvelopePDF _requestPDF__return = port.requestPDF(_requestPDF_envelopeID);
        System.out.println("requestPDF.result=" + _requestPDF__return);


        }
        {
        System.out.println("Invoking requestEnvelope...");
        java.lang.String _requestEnvelope_envelopeID = "";
        boolean _requestEnvelope_includeDocumentBytes = false;
        net.docusign.ws3_0.api.Envelope _requestEnvelope__return = port.requestEnvelope(_requestEnvelope_envelopeID, _requestEnvelope_includeDocumentBytes);
        System.out.println("requestEnvelope.result=" + _requestEnvelope__return);


        }
        {
        System.out.println("Invoking getAuthenticationToken...");
        java.lang.String _getAuthenticationToken_goToEnvelopeID = "";
        java.lang.String _getAuthenticationToken__return = port.getAuthenticationToken(_getAuthenticationToken_goToEnvelopeID);
        System.out.println("getAuthenticationToken.result=" + _getAuthenticationToken__return);


        }
        {
        System.out.println("Invoking requestPDFWithCert...");
        java.lang.String _requestPDFWithCert_envelopeID = "";
        boolean _requestPDFWithCert_addWaterMark = false;
        net.docusign.ws3_0.api.EnvelopePDF _requestPDFWithCert__return = port.requestPDFWithCert(_requestPDFWithCert_envelopeID, _requestPDFWithCert_addWaterMark);
        System.out.println("requestPDFWithCert.result=" + _requestPDFWithCert__return);


        }
        {
        System.out.println("Invoking createEnvelopeFromTemplates...");
        net.docusign.ws3_0.api.ArrayOfTemplateReference _createEnvelopeFromTemplates_templateReferences = null;
        net.docusign.ws3_0.api.ArrayOfRecipient1 _createEnvelopeFromTemplates_recipients = null;
        net.docusign.ws3_0.api.EnvelopeInformation _createEnvelopeFromTemplates_envelopeInformation = null;
        boolean _createEnvelopeFromTemplates_activateEnvelope = false;
        net.docusign.ws3_0.api.EnvelopeStatus _createEnvelopeFromTemplates__return = port.createEnvelopeFromTemplates(_createEnvelopeFromTemplates_templateReferences, _createEnvelopeFromTemplates_recipients, _createEnvelopeFromTemplates_envelopeInformation, _createEnvelopeFromTemplates_activateEnvelope);
        System.out.println("createEnvelopeFromTemplates.result=" + _createEnvelopeFromTemplates__return);


        }
        {
        System.out.println("Invoking createEnvelope...");
        net.docusign.ws3_0.api.Envelope _createEnvelope_envelope = null;
        net.docusign.ws3_0.api.EnvelopeStatus _createEnvelope__return = port.createEnvelope(_createEnvelope_envelope);
        System.out.println("createEnvelope.result=" + _createEnvelope__return);


        }
        {
        System.out.println("Invoking getFolders...");
        java.lang.String _getFolders_accountId = "";
        net.docusign.ws3_0.api.AvailableFolders _getFolders__return = port.getFolders(_getFolders_accountId);
        System.out.println("getFolders.result=" + _getFolders__return);


        }
        {
        System.out.println("Invoking getFolder...");
        java.lang.String _getFolder_accountId = "";
        net.docusign.ws3_0.api.FolderType _getFolder_folderType = null;
        java.lang.String _getFolder_folderName = "";
        int _getFolder_startPosition = 0;
        javax.xml.datatype.XMLGregorianCalendar _getFolder_fromDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getFolder_toDate = null;
        java.lang.String _getFolder_searchText = "";
        net.docusign.ws3_0.api.EnvelopeStatusCode _getFolder_status = null;
        net.docusign.ws3_0.api.FolderResults _getFolder__return = port.getFolder(_getFolder_accountId, _getFolder_folderType, _getFolder_folderName, _getFolder_startPosition, _getFolder_fromDate, _getFolder_toDate, _getFolder_searchText, _getFolder_status);
        System.out.println("getFolder.result=" + _getFolder__return);


        }
        {
        System.out.println("Invoking acknowledgeAuthoritativeCopyExport...");
        java.lang.String _acknowledgeAuthoritativeCopyExport_envelopeId = "";
        java.lang.String _acknowledgeAuthoritativeCopyExport_transactionId = "";
        byte[] _acknowledgeAuthoritativeCopyExport_checkSumHash = new byte[0];
        net.docusign.ws3_0.api.AuthoritativeCopyExportStatus _acknowledgeAuthoritativeCopyExport__return = port.acknowledgeAuthoritativeCopyExport(_acknowledgeAuthoritativeCopyExport_envelopeId, _acknowledgeAuthoritativeCopyExport_transactionId, _acknowledgeAuthoritativeCopyExport_checkSumHash);
        System.out.println("acknowledgeAuthoritativeCopyExport.result=" + _acknowledgeAuthoritativeCopyExport__return);


        }
        {
        System.out.println("Invoking uploadTemplate...");
        java.lang.String _uploadTemplate_templateXML = "";
        java.lang.String _uploadTemplate_accountID = "";
        boolean _uploadTemplate_shared = false;
        net.docusign.ws3_0.api.SaveTemplateResult _uploadTemplate__return = port.uploadTemplate(_uploadTemplate_templateXML, _uploadTemplate_accountID, _uploadTemplate_shared);
        System.out.println("uploadTemplate.result=" + _uploadTemplate__return);


        }
        {
        System.out.println("Invoking requestStatusesEx...");
        net.docusign.ws3_0.api.EnvelopeStatusFilter _requestStatusesEx_envelopeStatusFilter = null;
        net.docusign.ws3_0.api.FilteredEnvelopeStatuses _requestStatusesEx__return = port.requestStatusesEx(_requestStatusesEx_envelopeStatusFilter);
        System.out.println("requestStatusesEx.result=" + _requestStatusesEx__return);


        }
        {
        System.out.println("Invoking requestCorrectToken...");
        java.lang.String _requestCorrectToken_envelopeID = "";
        boolean _requestCorrectToken_suppressNavigation = false;
        java.lang.String _requestCorrectToken_returnURL = "";
        java.lang.String _requestCorrectToken__return = port.requestCorrectToken(_requestCorrectToken_envelopeID, _requestCorrectToken_suppressNavigation, _requestCorrectToken_returnURL);
        System.out.println("requestCorrectToken.result=" + _requestCorrectToken__return);


        }
        {
        System.out.println("Invoking createAndSendEnvelope...");
        net.docusign.ws3_0.api.Envelope _createAndSendEnvelope_envelope = null;
        net.docusign.ws3_0.api.EnvelopeStatus _createAndSendEnvelope__return = port.createAndSendEnvelope(_createAndSendEnvelope_envelope);
        System.out.println("createAndSendEnvelope.result=" + _createAndSendEnvelope__return);


        }
        {
        System.out.println("Invoking getAddressBookItems...");
        java.lang.String _getAddressBookItems_accountID = "";
        net.docusign.ws3_0.api.ArrayOfAddressBookItem _getAddressBookItems__return = port.getAddressBookItems(_getAddressBookItems_accountID);
        System.out.println("getAddressBookItems.result=" + _getAddressBookItems__return);


        }
        {
        System.out.println("Invoking requestStatusEx...");
        java.lang.String _requestStatusEx_envelopeID = "";
        net.docusign.ws3_0.api.EnvelopeStatus _requestStatusEx__return = port.requestStatusEx(_requestStatusEx_envelopeID);
        System.out.println("requestStatusEx.result=" + _requestStatusEx__return);


        }
        {
        System.out.println("Invoking getAccountMembershipFeaturesList...");
        java.lang.String _getAccountMembershipFeaturesList_accountId = "";
        net.docusign.ws3_0.api.AccountMembershipFeaturesList _getAccountMembershipFeaturesList__return = port.getAccountMembershipFeaturesList(_getAccountMembershipFeaturesList_accountId);
        System.out.println("getAccountMembershipFeaturesList.result=" + _getAccountMembershipFeaturesList__return);


        }
        {
        System.out.println("Invoking getRecipientList...");
        java.lang.String _getRecipientList_senderAccountId = "";
        java.lang.String _getRecipientList_recipientEmail = "";
        net.docusign.ws3_0.api.RecipientList _getRecipientList__return = port.getRecipientList(_getRecipientList_senderAccountId, _getRecipientList_recipientEmail);
        System.out.println("getRecipientList.result=" + _getRecipientList__return);


        }
        {
        System.out.println("Invoking synchEnvelope...");
        java.lang.String _synchEnvelope_transactionID = "";
        java.lang.String _synchEnvelope_accountID = "";
        boolean _synchEnvelope_block = false;
        net.docusign.ws3_0.api.SynchEnvelopeStatus _synchEnvelope__return = port.synchEnvelope(_synchEnvelope_transactionID, _synchEnvelope_accountID, _synchEnvelope_block);
        System.out.println("synchEnvelope.result=" + _synchEnvelope__return);


        }
        {
        System.out.println("Invoking updateAddressBookItems...");
        net.docusign.ws3_0.api.ArrayOfAddressBookItem _updateAddressBookItems_addressBookItems = null;
        boolean _updateAddressBookItems_returnAddressBook = false;
        net.docusign.ws3_0.api.UpdateAddressBookResult _updateAddressBookItems__return = port.updateAddressBookItems(_updateAddressBookItems_addressBookItems, _updateAddressBookItems_returnAddressBook);
        System.out.println("updateAddressBookItems.result=" + _updateAddressBookItems__return);


        }
        {
        System.out.println("Invoking getStatusInDocuSignConnectFormat...");
        java.lang.String _getStatusInDocuSignConnectFormat_envelopeID = "";
        net.docusign.ws3_0.api.DocuSignEnvelopeInformation _getStatusInDocuSignConnectFormat__return = port.getStatusInDocuSignConnectFormat(_getStatusInDocuSignConnectFormat_envelopeID);
        System.out.println("getStatusInDocuSignConnectFormat.result=" + _getStatusInDocuSignConnectFormat__return);


        }
        {
        System.out.println("Invoking getAccountSettingsList...");
        java.lang.String _getAccountSettingsList_accountId = "";
        net.docusign.ws3_0.api.AccountSettingsList _getAccountSettingsList__return = port.getAccountSettingsList(_getAccountSettingsList_accountId);
        System.out.println("getAccountSettingsList.result=" + _getAccountSettingsList__return);


        }
        {
        System.out.println("Invoking requestDocumentPDFsEx...");
        java.lang.String _requestDocumentPDFsEx_envelopeID = "";
        net.docusign.ws3_0.api.DocumentPDFs _requestDocumentPDFsEx__return = port.requestDocumentPDFsEx(_requestDocumentPDFsEx_envelopeID);
        System.out.println("requestDocumentPDFsEx.result=" + _requestDocumentPDFsEx__return);


        }
        {
        System.out.println("Invoking removeAddressBookItems...");
        net.docusign.ws3_0.api.ArrayOfAddressBookRemoveItem _removeAddressBookItems_addressBookRemoveItems = null;
        boolean _removeAddressBookItems_returnAddressBook = false;
        net.docusign.ws3_0.api.UpdateAddressBookResult _removeAddressBookItems__return = port.removeAddressBookItems(_removeAddressBookItems_addressBookRemoveItems, _removeAddressBookItems_returnAddressBook);
        System.out.println("removeAddressBookItems.result=" + _removeAddressBookItems__return);


        }
        {
        System.out.println("Invoking saveTemplate...");
        net.docusign.ws3_0.api.EnvelopeTemplate _saveTemplate_envelopeTemplate = null;
        net.docusign.ws3_0.api.SaveTemplateResult _saveTemplate__return = port.saveTemplate(_saveTemplate_envelopeTemplate);
        System.out.println("saveTemplate.result=" + _saveTemplate__return);


        }
        {
        System.out.println("Invoking ping...");
        boolean _ping__return = port.ping();
        System.out.println("ping.result=" + _ping__return);


        }
        {
        System.out.println("Invoking getRecipientEsignList...");
        java.lang.String _getRecipientEsignList_userName = "";
        java.lang.String _getRecipientEsignList_senderEmail = "";
        java.lang.String _getRecipientEsignList_senderAccountId = "";
        java.lang.String _getRecipientEsignList_recipientEmail = "";
        net.docusign.ws3_0.api.RecipientEsignList _getRecipientEsignList__return = port.getRecipientEsignList(_getRecipientEsignList_userName, _getRecipientEsignList_senderEmail, _getRecipientEsignList_senderAccountId, _getRecipientEsignList_recipientEmail);
        System.out.println("getRecipientEsignList.result=" + _getRecipientEsignList__return);


        }
        {
        System.out.println("Invoking requestStatuses...");
        net.docusign.ws3_0.api.EnvelopeStatusFilter _requestStatuses_envelopeStatusFilter = null;
        net.docusign.ws3_0.api.FilteredEnvelopeStatuses _requestStatuses__return = port.requestStatuses(_requestStatuses_envelopeStatusFilter);
        System.out.println("requestStatuses.result=" + _requestStatuses__return);


        }
        {
        System.out.println("Invoking correctAndResendEnvelope...");
        net.docusign.ws3_0.api.Correction _correctAndResendEnvelope_correction = null;
        net.docusign.ws3_0.api.CorrectionStatus _correctAndResendEnvelope__return = port.correctAndResendEnvelope(_correctAndResendEnvelope_correction);
        System.out.println("correctAndResendEnvelope.result=" + _correctAndResendEnvelope__return);


        }
        {
        System.out.println("Invoking requestDocumentPDFsRecipientsView...");
        java.lang.String _requestDocumentPDFsRecipientsView_envelopeID = "";
        java.lang.String _requestDocumentPDFsRecipientsView_recipientName = "";
        java.lang.String _requestDocumentPDFsRecipientsView_recipientEmail = "";
        net.docusign.ws3_0.api.DocumentPDFs _requestDocumentPDFsRecipientsView__return = port.requestDocumentPDFsRecipientsView(_requestDocumentPDFsRecipientsView_envelopeID, _requestDocumentPDFsRecipientsView_recipientName, _requestDocumentPDFsRecipientsView_recipientEmail);
        System.out.println("requestDocumentPDFsRecipientsView.result=" + _requestDocumentPDFsRecipientsView__return);


        }
        {
        System.out.println("Invoking transferEnvelope...");
        java.lang.String _transferEnvelope_envelopeID = "";
        java.lang.String _transferEnvelope_accountID = "";
        java.lang.String _transferEnvelope_userID = "";
        net.docusign.ws3_0.api.TransferEnvelopeStatus _transferEnvelope__return = port.transferEnvelope(_transferEnvelope_envelopeID, _transferEnvelope_accountID, _transferEnvelope_userID);
        System.out.println("transferEnvelope.result=" + _transferEnvelope__return);


        }
        {
        System.out.println("Invoking requestSenderToken...");
        java.lang.String _requestSenderToken_envelopeID = "";
        java.lang.String _requestSenderToken_accountID = "";
        java.lang.String _requestSenderToken_returnURL = "";
        java.lang.String _requestSenderToken__return = port.requestSenderToken(_requestSenderToken_envelopeID, _requestSenderToken_accountID, _requestSenderToken_returnURL);
        System.out.println("requestSenderToken.result=" + _requestSenderToken__return);


        }
        {
        System.out.println("Invoking envelopeAuditEvents...");
        java.lang.String _envelopeAuditEvents_envelopeId = "";
        net.docusign.ws3_0.api.EnvelopeAuditEventsResponse.EnvelopeAuditEventsResult _envelopeAuditEvents__return = port.envelopeAuditEvents(_envelopeAuditEvents_envelopeId);
        System.out.println("envelopeAuditEvents.result=" + _envelopeAuditEvents__return);


        }
        {
        System.out.println("Invoking exportAuthoritativeCopy...");
        java.lang.String _exportAuthoritativeCopy_envelopeId = "";
        net.docusign.ws3_0.api.AuthoritativeCopyExportDocuments _exportAuthoritativeCopy__return = port.exportAuthoritativeCopy(_exportAuthoritativeCopy_envelopeId);
        System.out.println("exportAuthoritativeCopy.result=" + _exportAuthoritativeCopy__return);


        }
        {
        System.out.println("Invoking sendEnvelope...");
        java.lang.String _sendEnvelope_envelopeId = "";
        java.lang.String _sendEnvelope_accountId = "";
        net.docusign.ws3_0.api.EnvelopeStatus _sendEnvelope__return = port.sendEnvelope(_sendEnvelope_envelopeId, _sendEnvelope_accountId);
        System.out.println("sendEnvelope.result=" + _sendEnvelope__return);


        }
        {
        System.out.println("Invoking voidEnvelope...");
        java.lang.String _voidEnvelope_envelopeID = "";
        java.lang.String _voidEnvelope_reason = "";
        net.docusign.ws3_0.api.VoidEnvelopeStatus _voidEnvelope__return = port.voidEnvelope(_voidEnvelope_envelopeID, _voidEnvelope_reason);
        System.out.println("voidEnvelope.result=" + _voidEnvelope__return);


        }
        {
        System.out.println("Invoking purgeDocuments...");
        java.lang.String _purgeDocuments_envelopeID = "";
        net.docusign.ws3_0.api.PurgeDocumentStatus _purgeDocuments__return = port.purgeDocuments(_purgeDocuments_envelopeID);
        System.out.println("purgeDocuments.result=" + _purgeDocuments__return);


        }
        {
        System.out.println("Invoking requestStatus...");
        java.lang.String _requestStatus_envelopeID = "";
        net.docusign.ws3_0.api.EnvelopeStatus _requestStatus__return = port.requestStatus(_requestStatus_envelopeID);
        System.out.println("requestStatus.result=" + _requestStatus__return);


        }
        {
        System.out.println("Invoking requestPDFNoWaterMark...");
        java.lang.String _requestPDFNoWaterMark_envelopeID = "";
        net.docusign.ws3_0.api.EnvelopePDF _requestPDFNoWaterMark__return = port.requestPDFNoWaterMark(_requestPDFNoWaterMark_envelopeID);
        System.out.println("requestPDFNoWaterMark.result=" + _requestPDFNoWaterMark__return);


        }

        System.exit(0);
    }

}
