/*
Copyright (C) DocuSign, Inc.  All rights reserved.

This source code is intended only as a supplement to DocuSign SDK and/or on-line documentation.

This sample is designed to demonstrate DocuSign features and is not intended for production use.
Code and policy for a production application must be developed to meet the specific data and
security requirements of the application.

THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
FITNESS FOR A PARTICULAR PURPOSE.
*/

package net.docusign.ws3_0.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Sep 27 16:58:56 EEST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://www.docusign.net/API/3.0", name = "APIServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface APIServiceSoap {

    @WebResult(name = "RequestTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestTemplate")
    @WebMethod(operationName = "RequestTemplate", action = "http://www.docusign.net/API/3.0/RequestTemplate")
    @ResponseWrapper(localName = "RequestTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestTemplateResponse")
    public net.docusign.ws3_0.api.EnvelopeTemplate requestTemplate(
        @WebParam(name = "TemplateID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String templateID,
        @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeDocumentBytes
    );

    @WebResult(name = "RequestTemplatesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestTemplates", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestTemplates")
    @WebMethod(operationName = "RequestTemplates", action = "http://www.docusign.net/API/3.0/RequestTemplates")
    @ResponseWrapper(localName = "RequestTemplatesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestTemplatesResponse")
    public net.docusign.ws3_0.api.EnvelopeTemplates requestTemplates(
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountID,
        @WebParam(name = "IncludeAdvancedTemplates", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeAdvancedTemplates
    );

    @WebResult(name = "RequestRecipientTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestRecipientToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestRecipientToken")
    @WebMethod(operationName = "RequestRecipientToken", action = "http://www.docusign.net/API/3.0/RequestRecipientToken")
    @ResponseWrapper(localName = "RequestRecipientTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestRecipientTokenResponse")
    public java.lang.String requestRecipientToken(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID,
        @WebParam(name = "ClientUserID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String clientUserID,
        @WebParam(name = "Username", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String username,
        @WebParam(name = "Email", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String email,
        @WebParam(name = "AuthenticationAssertion", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.RequestRecipientTokenAuthenticationAssertion authenticationAssertion,
        @WebParam(name = "ClientURLs", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.RequestRecipientTokenClientURLs clientURLs
    );

    @WebResult(name = "RequestDocumentPDFsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFs", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestDocumentPDFs")
    @WebMethod(operationName = "RequestDocumentPDFs", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFs")
    @ResponseWrapper(localName = "RequestDocumentPDFsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestDocumentPDFsResponse")
    public net.docusign.ws3_0.api.DocumentPDFs requestDocumentPDFs(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID
    );

    @WebResult(name = "CreateEnvelopeFromTemplatesAndFormsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelopeFromTemplatesAndForms", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CreateEnvelopeFromTemplatesAndForms")
    @WebMethod(operationName = "CreateEnvelopeFromTemplatesAndForms", action = "http://www.docusign.net/API/3.0/CreateEnvelopeFromTemplatesAndForms")
    @ResponseWrapper(localName = "CreateEnvelopeFromTemplatesAndFormsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CreateEnvelopeFromTemplatesAndFormsResponse")
    public net.docusign.ws3_0.api.EnvelopeStatus createEnvelopeFromTemplatesAndForms(
        @WebParam(name = "EnvelopeInformation", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.EnvelopeInformation envelopeInformation,
        @WebParam(name = "CompositeTemplates", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.ArrayOfCompositeTemplate compositeTemplates,
        @WebParam(name = "ActivateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean activateEnvelope
    );

    @WebResult(name = "RequestPDFResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDF", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestPDF")
    @WebMethod(operationName = "RequestPDF", action = "http://www.docusign.net/API/3.0/RequestPDF")
    @ResponseWrapper(localName = "RequestPDFResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestPDFResponse")
    public net.docusign.ws3_0.api.EnvelopePDF requestPDF(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID
    );

    @WebResult(name = "RequestEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestEnvelope")
    @WebMethod(operationName = "RequestEnvelope", action = "http://www.docusign.net/API/3.0/RequestEnvelope")
    @ResponseWrapper(localName = "RequestEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestEnvelopeResponse")
    public net.docusign.ws3_0.api.Envelope requestEnvelope(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID,
        @WebParam(name = "IncludeDocumentBytes", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean includeDocumentBytes
    );

    @WebResult(name = "GetAuthenticationTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAuthenticationToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetAuthenticationToken")
    @WebMethod(operationName = "GetAuthenticationToken", action = "http://www.docusign.net/API/3.0/GetAuthenticationToken")
    @ResponseWrapper(localName = "GetAuthenticationTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetAuthenticationTokenResponse")
    public java.lang.String getAuthenticationToken(
        @WebParam(name = "GoToEnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String goToEnvelopeID
    );

    @WebResult(name = "RequestPDFWithCertResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFWithCert", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestPDFWithCert")
    @WebMethod(operationName = "RequestPDFWithCert", action = "http://www.docusign.net/API/3.0/RequestPDFWithCert")
    @ResponseWrapper(localName = "RequestPDFWithCertResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestPDFWithCertResponse")
    public net.docusign.ws3_0.api.EnvelopePDF requestPDFWithCert(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID,
        @WebParam(name = "AddWaterMark", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean addWaterMark
    );

    @WebResult(name = "CreateEnvelopeFromTemplatesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelopeFromTemplates", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CreateEnvelopeFromTemplates")
    @WebMethod(operationName = "CreateEnvelopeFromTemplates", action = "http://www.docusign.net/API/3.0/CreateEnvelopeFromTemplates")
    @ResponseWrapper(localName = "CreateEnvelopeFromTemplatesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CreateEnvelopeFromTemplatesResponse")
    public net.docusign.ws3_0.api.EnvelopeStatus createEnvelopeFromTemplates(
        @WebParam(name = "TemplateReferences", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.ArrayOfTemplateReference templateReferences,
        @WebParam(name = "Recipients", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.ArrayOfRecipient1 recipients,
        @WebParam(name = "EnvelopeInformation", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.EnvelopeInformation envelopeInformation,
        @WebParam(name = "ActivateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean activateEnvelope
    );

    @WebResult(name = "CreateEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CreateEnvelope")
    @WebMethod(operationName = "CreateEnvelope", action = "http://www.docusign.net/API/3.0/CreateEnvelope")
    @ResponseWrapper(localName = "CreateEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CreateEnvelopeResponse")
    public net.docusign.ws3_0.api.EnvelopeStatus createEnvelope(
        @WebParam(name = "Envelope", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.Envelope envelope
    );

    @WebResult(name = "GetFoldersResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetFolders", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetFolders")
    @WebMethod(operationName = "GetFolders", action = "http://www.docusign.net/API/3.0/GetFolders")
    @ResponseWrapper(localName = "GetFoldersResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetFoldersResponse")
    public net.docusign.ws3_0.api.AvailableFolders getFolders(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountId
    );

    @WebResult(name = "GetFolderResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetFolder", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetFolder")
    @WebMethod(operationName = "GetFolder", action = "http://www.docusign.net/API/3.0/GetFolder")
    @ResponseWrapper(localName = "GetFolderResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetFolderResponse")
    public net.docusign.ws3_0.api.FolderResults getFolder(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountId,
        @WebParam(name = "FolderType", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.FolderType folderType,
        @WebParam(name = "FolderName", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String folderName,
        @WebParam(name = "StartPosition", targetNamespace = "http://www.docusign.net/API/3.0")
        int startPosition,
        @WebParam(name = "FromDate", targetNamespace = "http://www.docusign.net/API/3.0")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.docusign.net/API/3.0")
        javax.xml.datatype.XMLGregorianCalendar toDate,
        @WebParam(name = "SearchText", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String searchText,
        @WebParam(name = "Status", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.EnvelopeStatusCode status
    );

    @WebResult(name = "AcknowledgeAuthoritativeCopyExportResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "AcknowledgeAuthoritativeCopyExport", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.AcknowledgeAuthoritativeCopyExport")
    @WebMethod(operationName = "AcknowledgeAuthoritativeCopyExport", action = "http://www.docusign.net/API/3.0/AcknowledgeAuthoritativeCopyExport")
    @ResponseWrapper(localName = "AcknowledgeAuthoritativeCopyExportResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.AcknowledgeAuthoritativeCopyExportResponse")
    public net.docusign.ws3_0.api.AuthoritativeCopyExportStatus acknowledgeAuthoritativeCopyExport(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeId,
        @WebParam(name = "TransactionId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String transactionId,
        @WebParam(name = "checkSumHash", targetNamespace = "http://www.docusign.net/API/3.0")
        byte[] checkSumHash
    );

    @WebResult(name = "UploadTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "UploadTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.UploadTemplate")
    @WebMethod(operationName = "UploadTemplate", action = "http://www.docusign.net/API/3.0/UploadTemplate")
    @ResponseWrapper(localName = "UploadTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.UploadTemplateResponse")
    public net.docusign.ws3_0.api.SaveTemplateResult uploadTemplate(
        @WebParam(name = "TemplateXML", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String templateXML,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountID,
        @WebParam(name = "Shared", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean shared
    );

    @WebResult(name = "RequestStatusesExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusesEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestStatusesEx")
    @WebMethod(operationName = "RequestStatusesEx", action = "http://www.docusign.net/API/3.0/RequestStatusesEx")
    @ResponseWrapper(localName = "RequestStatusesExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestStatusesExResponse")
    public net.docusign.ws3_0.api.FilteredEnvelopeStatuses requestStatusesEx(
        @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.EnvelopeStatusFilter envelopeStatusFilter
    );

    @WebResult(name = "RequestCorrectTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestCorrectToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestCorrectToken")
    @WebMethod(operationName = "RequestCorrectToken", action = "http://www.docusign.net/API/3.0/RequestCorrectToken")
    @ResponseWrapper(localName = "RequestCorrectTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestCorrectTokenResponse")
    public java.lang.String requestCorrectToken(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID,
        @WebParam(name = "SuppressNavigation", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean suppressNavigation,
        @WebParam(name = "ReturnURL", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String returnURL
    );

    @WebResult(name = "CreateAndSendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CreateAndSendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CreateAndSendEnvelope")
    @WebMethod(operationName = "CreateAndSendEnvelope", action = "http://www.docusign.net/API/3.0/CreateAndSendEnvelope")
    @ResponseWrapper(localName = "CreateAndSendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CreateAndSendEnvelopeResponse")
    public net.docusign.ws3_0.api.EnvelopeStatus createAndSendEnvelope(
        @WebParam(name = "Envelope", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.Envelope envelope
    );

    @WebResult(name = "GetAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetAddressBookItems")
    @WebMethod(operationName = "GetAddressBookItems", action = "http://www.docusign.net/API/3.0/GetAddressBookItems")
    @ResponseWrapper(localName = "GetAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetAddressBookItemsResponse")
    public net.docusign.ws3_0.api.ArrayOfAddressBookItem getAddressBookItems(
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountID
    );

    @WebResult(name = "RequestStatusExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatusEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestStatusEx")
    @WebMethod(operationName = "RequestStatusEx", action = "http://www.docusign.net/API/3.0/RequestStatusEx")
    @ResponseWrapper(localName = "RequestStatusExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestStatusExResponse")
    public net.docusign.ws3_0.api.EnvelopeStatus requestStatusEx(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID
    );

    @WebResult(name = "GetAccountMembershipFeaturesListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAccountMembershipFeaturesList", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetAccountMembershipFeaturesList")
    @WebMethod(operationName = "GetAccountMembershipFeaturesList", action = "http://www.docusign.net/API/3.0/GetAccountMembershipFeaturesList")
    @ResponseWrapper(localName = "GetAccountMembershipFeaturesListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetAccountMembershipFeaturesListResponse")
    public net.docusign.ws3_0.api.AccountMembershipFeaturesList getAccountMembershipFeaturesList(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountId
    );

    @WebResult(name = "GetRecipientListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetRecipientList", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetRecipientList")
    @WebMethod(operationName = "GetRecipientList", action = "http://www.docusign.net/API/3.0/GetRecipientList")
    @ResponseWrapper(localName = "GetRecipientListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetRecipientListResponse")
    public net.docusign.ws3_0.api.RecipientList getRecipientList(
        @WebParam(name = "SenderAccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String senderAccountId,
        @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String recipientEmail
    );

    @WebResult(name = "SynchEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SynchEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.SynchEnvelope")
    @WebMethod(operationName = "SynchEnvelope", action = "http://www.docusign.net/API/3.0/SynchEnvelope")
    @ResponseWrapper(localName = "SynchEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.SynchEnvelopeResponse")
    public net.docusign.ws3_0.api.SynchEnvelopeStatus synchEnvelope(
        @WebParam(name = "TransactionID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String transactionID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountID,
        @WebParam(name = "Block", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean block
    );

    @WebResult(name = "UpdateAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "UpdateAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.UpdateAddressBookItems")
    @WebMethod(operationName = "UpdateAddressBookItems", action = "http://www.docusign.net/API/3.0/UpdateAddressBookItems")
    @ResponseWrapper(localName = "UpdateAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.UpdateAddressBookItemsResponse")
    public net.docusign.ws3_0.api.UpdateAddressBookResult updateAddressBookItems(
        @WebParam(name = "AddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.ArrayOfAddressBookItem addressBookItems,
        @WebParam(name = "ReturnAddressBook", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean returnAddressBook
    );

    @WebResult(name = "GetStatusInDocuSignConnectFormatResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetStatusInDocuSignConnectFormat", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetStatusInDocuSignConnectFormat")
    @WebMethod(operationName = "GetStatusInDocuSignConnectFormat", action = "http://www.docusign.net/API/3.0/GetStatusInDocuSignConnectFormat")
    @ResponseWrapper(localName = "GetStatusInDocuSignConnectFormatResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetStatusInDocuSignConnectFormatResponse")
    public net.docusign.ws3_0.api.DocuSignEnvelopeInformation getStatusInDocuSignConnectFormat(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID
    );

    @WebResult(name = "GetAccountSettingsListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetAccountSettingsList", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetAccountSettingsList")
    @WebMethod(operationName = "GetAccountSettingsList", action = "http://www.docusign.net/API/3.0/GetAccountSettingsList")
    @ResponseWrapper(localName = "GetAccountSettingsListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetAccountSettingsListResponse")
    public net.docusign.ws3_0.api.AccountSettingsList getAccountSettingsList(
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountId
    );

    @WebResult(name = "RequestDocumentPDFsExResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFsEx", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestDocumentPDFsEx")
    @WebMethod(operationName = "RequestDocumentPDFsEx", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFsEx")
    @ResponseWrapper(localName = "RequestDocumentPDFsExResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestDocumentPDFsExResponse")
    public net.docusign.ws3_0.api.DocumentPDFs requestDocumentPDFsEx(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID
    );

    @WebResult(name = "RemoveAddressBookItemsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RemoveAddressBookItems", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RemoveAddressBookItems")
    @WebMethod(operationName = "RemoveAddressBookItems", action = "http://www.docusign.net/API/3.0/RemoveAddressBookItems")
    @ResponseWrapper(localName = "RemoveAddressBookItemsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RemoveAddressBookItemsResponse")
    public net.docusign.ws3_0.api.UpdateAddressBookResult removeAddressBookItems(
        @WebParam(name = "AddressBookRemoveItems", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.ArrayOfAddressBookRemoveItem addressBookRemoveItems,
        @WebParam(name = "ReturnAddressBook", targetNamespace = "http://www.docusign.net/API/3.0")
        boolean returnAddressBook
    );

    @WebResult(name = "SaveTemplateResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SaveTemplate", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.SaveTemplate")
    @WebMethod(operationName = "SaveTemplate", action = "http://www.docusign.net/API/3.0/SaveTemplate")
    @ResponseWrapper(localName = "SaveTemplateResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.SaveTemplateResponse")
    public net.docusign.ws3_0.api.SaveTemplateResult saveTemplate(
        @WebParam(name = "EnvelopeTemplate", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.EnvelopeTemplate envelopeTemplate
    );

    @WebResult(name = "PingResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.Ping")
    @WebMethod(operationName = "Ping", action = "http://www.docusign.net/API/3.0/Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.PingResponse")
    public boolean ping();

    @WebResult(name = "GetRecipientEsignListResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "GetRecipientEsignList", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetRecipientEsignList")
    @WebMethod(operationName = "GetRecipientEsignList", action = "http://www.docusign.net/API/3.0/GetRecipientEsignList")
    @ResponseWrapper(localName = "GetRecipientEsignListResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.GetRecipientEsignListResponse")
    public net.docusign.ws3_0.api.RecipientEsignList getRecipientEsignList(
        @WebParam(name = "UserName", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String userName,
        @WebParam(name = "SenderEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String senderEmail,
        @WebParam(name = "SenderAccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String senderAccountId,
        @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String recipientEmail
    );

    @WebResult(name = "RequestStatusesResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatuses", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestStatuses")
    @WebMethod(operationName = "RequestStatuses", action = "http://www.docusign.net/API/3.0/RequestStatuses")
    @ResponseWrapper(localName = "RequestStatusesResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestStatusesResponse")
    public net.docusign.ws3_0.api.FilteredEnvelopeStatuses requestStatuses(
        @WebParam(name = "EnvelopeStatusFilter", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.EnvelopeStatusFilter envelopeStatusFilter
    );

    @WebResult(name = "CorrectAndResendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "CorrectAndResendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CorrectAndResendEnvelope")
    @WebMethod(operationName = "CorrectAndResendEnvelope", action = "http://www.docusign.net/API/3.0/CorrectAndResendEnvelope")
    @ResponseWrapper(localName = "CorrectAndResendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.CorrectAndResendEnvelopeResponse")
    public net.docusign.ws3_0.api.CorrectionStatus correctAndResendEnvelope(
        @WebParam(name = "Correction", targetNamespace = "http://www.docusign.net/API/3.0")
        net.docusign.ws3_0.api.Correction correction
    );

    @WebResult(name = "RequestDocumentPDFsRecipientsViewResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestDocumentPDFsRecipientsView", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestDocumentPDFsRecipientsView")
    @WebMethod(operationName = "RequestDocumentPDFsRecipientsView", action = "http://www.docusign.net/API/3.0/RequestDocumentPDFsRecipientsView")
    @ResponseWrapper(localName = "RequestDocumentPDFsRecipientsViewResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestDocumentPDFsRecipientsViewResponse")
    public net.docusign.ws3_0.api.DocumentPDFs requestDocumentPDFsRecipientsView(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID,
        @WebParam(name = "RecipientName", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String recipientName,
        @WebParam(name = "RecipientEmail", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String recipientEmail
    );

    @WebResult(name = "TransferEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "TransferEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.TransferEnvelope")
    @WebMethod(operationName = "TransferEnvelope", action = "http://www.docusign.net/API/3.0/TransferEnvelope")
    @ResponseWrapper(localName = "TransferEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.TransferEnvelopeResponse")
    public net.docusign.ws3_0.api.TransferEnvelopeStatus transferEnvelope(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountID,
        @WebParam(name = "UserID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String userID
    );

    @WebResult(name = "RequestSenderTokenResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestSenderToken", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestSenderToken")
    @WebMethod(operationName = "RequestSenderToken", action = "http://www.docusign.net/API/3.0/RequestSenderToken")
    @ResponseWrapper(localName = "RequestSenderTokenResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestSenderTokenResponse")
    public java.lang.String requestSenderToken(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountID,
        @WebParam(name = "ReturnURL", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String returnURL
    );

    @WebResult(name = "EnvelopeAuditEventsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "EnvelopeAuditEvents", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.EnvelopeAuditEvents")
    @WebMethod(operationName = "EnvelopeAuditEvents", action = "http://www.docusign.net/API/3.0/EnvelopeAuditEvents")
    @ResponseWrapper(localName = "EnvelopeAuditEventsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.EnvelopeAuditEventsResponse")
    public net.docusign.ws3_0.api.EnvelopeAuditEventsResponse.EnvelopeAuditEventsResult envelopeAuditEvents(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeId
    );

    @WebResult(name = "ExportAuthoritativeCopyResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "ExportAuthoritativeCopy", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.ExportAuthoritativeCopy")
    @WebMethod(operationName = "ExportAuthoritativeCopy", action = "http://www.docusign.net/API/3.0/ExportAuthoritativeCopy")
    @ResponseWrapper(localName = "ExportAuthoritativeCopyResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.ExportAuthoritativeCopyResponse")
    public net.docusign.ws3_0.api.AuthoritativeCopyExportDocuments exportAuthoritativeCopy(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeId
    );

    @WebResult(name = "SendEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "SendEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.SendEnvelope")
    @WebMethod(operationName = "SendEnvelope", action = "http://www.docusign.net/API/3.0/SendEnvelope")
    @ResponseWrapper(localName = "SendEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.SendEnvelopeResponse")
    public net.docusign.ws3_0.api.EnvelopeStatus sendEnvelope(
        @WebParam(name = "EnvelopeId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeId,
        @WebParam(name = "AccountId", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String accountId
    );

    @WebResult(name = "VoidEnvelopeResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "VoidEnvelope", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.VoidEnvelope")
    @WebMethod(operationName = "VoidEnvelope", action = "http://www.docusign.net/API/3.0/VoidEnvelope")
    @ResponseWrapper(localName = "VoidEnvelopeResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.VoidEnvelopeResponse")
    public net.docusign.ws3_0.api.VoidEnvelopeStatus voidEnvelope(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID,
        @WebParam(name = "Reason", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String reason
    );

    @WebResult(name = "PurgeDocumentsResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "PurgeDocuments", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.PurgeDocuments")
    @WebMethod(operationName = "PurgeDocuments", action = "http://www.docusign.net/API/3.0/PurgeDocuments")
    @ResponseWrapper(localName = "PurgeDocumentsResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.PurgeDocumentsResponse")
    public net.docusign.ws3_0.api.PurgeDocumentStatus purgeDocuments(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID
    );

    @WebResult(name = "RequestStatusResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestStatus", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestStatus")
    @WebMethod(operationName = "RequestStatus", action = "http://www.docusign.net/API/3.0/RequestStatus")
    @ResponseWrapper(localName = "RequestStatusResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestStatusResponse")
    public net.docusign.ws3_0.api.EnvelopeStatus requestStatus(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID
    );

    @WebResult(name = "RequestPDFNoWaterMarkResult", targetNamespace = "http://www.docusign.net/API/3.0")
    @RequestWrapper(localName = "RequestPDFNoWaterMark", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestPDFNoWaterMark")
    @WebMethod(operationName = "RequestPDFNoWaterMark", action = "http://www.docusign.net/API/3.0/RequestPDFNoWaterMark")
    @ResponseWrapper(localName = "RequestPDFNoWaterMarkResponse", targetNamespace = "http://www.docusign.net/API/3.0", className = "net.docusign.ws3_0.api.RequestPDFNoWaterMarkResponse")
    public net.docusign.ws3_0.api.EnvelopePDF requestPDFNoWaterMark(
        @WebParam(name = "EnvelopeID", targetNamespace = "http://www.docusign.net/API/3.0")
        java.lang.String envelopeID
    );
}
