//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signing.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] picturePdf {
            get {
                object obj = ResourceManager.GetObject("picturePdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;DocuSignDocumentTemplate xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; canAddTabs=&quot;true&quot; xmlns=&quot;http://www.docusign.net/API/3.0&quot;&gt;
        ///  &lt;Header&gt;
        ///    &lt;Name&gt;Terms of Agreement&lt;/Name&gt;
        ///    &lt;Version&gt;1.0&lt;/Version&gt;
        ///    &lt;Description&gt;Sample Terms of Agreement for Application&lt;/Description&gt;
        ///    &lt;Password&gt;
        ///    &lt;/Password&gt;
        ///    &lt;Subject&gt;
        ///    &lt;/Subject&gt;
        ///    &lt;Message&gt;
        ///    &lt;/Message&gt;
        ///    &lt;Vaulting&gt;None&lt;/Vaulting&gt;
        ///  &lt;/Header&gt;
        ///  &lt;Document&gt;
        ///    &lt;Name&gt;TERMS ONLY&lt;/Name&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sampleTemplate {
            get {
                return ResourceManager.GetString("sampleTemplate", resourceCulture);
            }
        }
    }
}
