//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceCo.CredentialService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://www.docusign.net/API/Credential")]
    [System.SerializableAttribute()]
    public partial class LoginResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InsuranceCo.CredentialService.ErrorCode ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InsuranceCo.CredentialService.Account[] AccountsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public InsuranceCo.CredentialService.ErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AuthenticationMessage {
            get {
                return this.AuthenticationMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationMessageField, value) != true)) {
                    this.AuthenticationMessageField = value;
                    this.RaisePropertyChanged("AuthenticationMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public InsuranceCo.CredentialService.Account[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCode", Namespace="http://www.docusign.net/API/Credential")]
    public enum ErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User_Does_Not_Exist_In_System = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Account_Lacks_Permissions = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User_Lacks_Permissions = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User_Authentication_Failed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified_Error = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://www.docusign.net/API/Credential")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIDField, value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.docusign.net/API/Credential", ConfigurationName="CredentialService.CredentialSoap")]
    public interface CredentialSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.docusign.net/API/Credential/Ping", ReplyAction="*")]
        bool Ping();
        
        // CODEGEN: Generating message contract since element name Email from namespace http://www.docusign.net/API/Credential is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.docusign.net/API/Credential/Login", ReplyAction="*")]
        InsuranceCo.CredentialService.LoginResponse Login(InsuranceCo.CredentialService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://www.docusign.net/API/Credential is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.docusign.net/API/Credential/GetAuthenticationToken", ReplyAction="*")]
        InsuranceCo.CredentialService.GetAuthenticationTokenResponse GetAuthenticationToken(InsuranceCo.CredentialService.GetAuthenticationTokenRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://www.docusign.net/API/Credential is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.docusign.net/API/Credential/RequestSenderToken", ReplyAction="*")]
        InsuranceCo.CredentialService.RequestSenderTokenResponse RequestSenderToken(InsuranceCo.CredentialService.RequestSenderTokenRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://www.docusign.net/API/Credential is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.docusign.net/API/Credential/RequestCorrectToken", ReplyAction="*")]
        InsuranceCo.CredentialService.RequestCorrectTokenResponse RequestCorrectToken(InsuranceCo.CredentialService.RequestCorrectTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://www.docusign.net/API/Credential", Order=0)]
        public InsuranceCo.CredentialService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(InsuranceCo.CredentialService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.docusign.net/API/Credential")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string Email, string Password) {
            this.Email = Email;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://www.docusign.net/API/Credential", Order=0)]
        public InsuranceCo.CredentialService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(InsuranceCo.CredentialService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.docusign.net/API/Credential")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsuranceCo.CredentialService.LoginResult LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(InsuranceCo.CredentialService.LoginResult LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthenticationTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthenticationToken", Namespace="http://www.docusign.net/API/Credential", Order=0)]
        public InsuranceCo.CredentialService.GetAuthenticationTokenRequestBody Body;
        
        public GetAuthenticationTokenRequest() {
        }
        
        public GetAuthenticationTokenRequest(InsuranceCo.CredentialService.GetAuthenticationTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.docusign.net/API/Credential")]
    public partial class GetAuthenticationTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GoToEnvelopeID;
        
        public GetAuthenticationTokenRequestBody() {
        }
        
        public GetAuthenticationTokenRequestBody(string Email, string Password, string AccountID, string GoToEnvelopeID) {
            this.Email = Email;
            this.Password = Password;
            this.AccountID = AccountID;
            this.GoToEnvelopeID = GoToEnvelopeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthenticationTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthenticationTokenResponse", Namespace="http://www.docusign.net/API/Credential", Order=0)]
        public InsuranceCo.CredentialService.GetAuthenticationTokenResponseBody Body;
        
        public GetAuthenticationTokenResponse() {
        }
        
        public GetAuthenticationTokenResponse(InsuranceCo.CredentialService.GetAuthenticationTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.docusign.net/API/Credential")]
    public partial class GetAuthenticationTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAuthenticationTokenResult;
        
        public GetAuthenticationTokenResponseBody() {
        }
        
        public GetAuthenticationTokenResponseBody(string GetAuthenticationTokenResult) {
            this.GetAuthenticationTokenResult = GetAuthenticationTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestSenderTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestSenderToken", Namespace="http://www.docusign.net/API/Credential", Order=0)]
        public InsuranceCo.CredentialService.RequestSenderTokenRequestBody Body;
        
        public RequestSenderTokenRequest() {
        }
        
        public RequestSenderTokenRequest(InsuranceCo.CredentialService.RequestSenderTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.docusign.net/API/Credential")]
    public partial class RequestSenderTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EnvelopeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReturnURL;
        
        public RequestSenderTokenRequestBody() {
        }
        
        public RequestSenderTokenRequestBody(string Email, string Password, string AccountID, string EnvelopeID, string ReturnURL) {
            this.Email = Email;
            this.Password = Password;
            this.AccountID = AccountID;
            this.EnvelopeID = EnvelopeID;
            this.ReturnURL = ReturnURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestSenderTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestSenderTokenResponse", Namespace="http://www.docusign.net/API/Credential", Order=0)]
        public InsuranceCo.CredentialService.RequestSenderTokenResponseBody Body;
        
        public RequestSenderTokenResponse() {
        }
        
        public RequestSenderTokenResponse(InsuranceCo.CredentialService.RequestSenderTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.docusign.net/API/Credential")]
    public partial class RequestSenderTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestSenderTokenResult;
        
        public RequestSenderTokenResponseBody() {
        }
        
        public RequestSenderTokenResponseBody(string RequestSenderTokenResult) {
            this.RequestSenderTokenResult = RequestSenderTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestCorrectTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestCorrectToken", Namespace="http://www.docusign.net/API/Credential", Order=0)]
        public InsuranceCo.CredentialService.RequestCorrectTokenRequestBody Body;
        
        public RequestCorrectTokenRequest() {
        }
        
        public RequestCorrectTokenRequest(InsuranceCo.CredentialService.RequestCorrectTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.docusign.net/API/Credential")]
    public partial class RequestCorrectTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EnvelopeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool SuppressNavigation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReturnURL;
        
        public RequestCorrectTokenRequestBody() {
        }
        
        public RequestCorrectTokenRequestBody(string Email, string Password, string EnvelopeID, bool SuppressNavigation, string ReturnURL) {
            this.Email = Email;
            this.Password = Password;
            this.EnvelopeID = EnvelopeID;
            this.SuppressNavigation = SuppressNavigation;
            this.ReturnURL = ReturnURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestCorrectTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestCorrectTokenResponse", Namespace="http://www.docusign.net/API/Credential", Order=0)]
        public InsuranceCo.CredentialService.RequestCorrectTokenResponseBody Body;
        
        public RequestCorrectTokenResponse() {
        }
        
        public RequestCorrectTokenResponse(InsuranceCo.CredentialService.RequestCorrectTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.docusign.net/API/Credential")]
    public partial class RequestCorrectTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestCorrectTokenResult;
        
        public RequestCorrectTokenResponseBody() {
        }
        
        public RequestCorrectTokenResponseBody(string RequestCorrectTokenResult) {
            this.RequestCorrectTokenResult = RequestCorrectTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CredentialSoapChannel : InsuranceCo.CredentialService.CredentialSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CredentialSoapClient : System.ServiceModel.ClientBase<InsuranceCo.CredentialService.CredentialSoap>, InsuranceCo.CredentialService.CredentialSoap {
        
        public CredentialSoapClient() {
        }
        
        public CredentialSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CredentialSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CredentialSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CredentialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsuranceCo.CredentialService.LoginResponse InsuranceCo.CredentialService.CredentialSoap.Login(InsuranceCo.CredentialService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public InsuranceCo.CredentialService.LoginResult Login(string Email, string Password) {
            InsuranceCo.CredentialService.LoginRequest inValue = new InsuranceCo.CredentialService.LoginRequest();
            inValue.Body = new InsuranceCo.CredentialService.LoginRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            InsuranceCo.CredentialService.LoginResponse retVal = ((InsuranceCo.CredentialService.CredentialSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsuranceCo.CredentialService.GetAuthenticationTokenResponse InsuranceCo.CredentialService.CredentialSoap.GetAuthenticationToken(InsuranceCo.CredentialService.GetAuthenticationTokenRequest request) {
            return base.Channel.GetAuthenticationToken(request);
        }
        
        public string GetAuthenticationToken(string Email, string Password, string AccountID, string GoToEnvelopeID) {
            InsuranceCo.CredentialService.GetAuthenticationTokenRequest inValue = new InsuranceCo.CredentialService.GetAuthenticationTokenRequest();
            inValue.Body = new InsuranceCo.CredentialService.GetAuthenticationTokenRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.AccountID = AccountID;
            inValue.Body.GoToEnvelopeID = GoToEnvelopeID;
            InsuranceCo.CredentialService.GetAuthenticationTokenResponse retVal = ((InsuranceCo.CredentialService.CredentialSoap)(this)).GetAuthenticationToken(inValue);
            return retVal.Body.GetAuthenticationTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsuranceCo.CredentialService.RequestSenderTokenResponse InsuranceCo.CredentialService.CredentialSoap.RequestSenderToken(InsuranceCo.CredentialService.RequestSenderTokenRequest request) {
            return base.Channel.RequestSenderToken(request);
        }
        
        public string RequestSenderToken(string Email, string Password, string AccountID, string EnvelopeID, string ReturnURL) {
            InsuranceCo.CredentialService.RequestSenderTokenRequest inValue = new InsuranceCo.CredentialService.RequestSenderTokenRequest();
            inValue.Body = new InsuranceCo.CredentialService.RequestSenderTokenRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.AccountID = AccountID;
            inValue.Body.EnvelopeID = EnvelopeID;
            inValue.Body.ReturnURL = ReturnURL;
            InsuranceCo.CredentialService.RequestSenderTokenResponse retVal = ((InsuranceCo.CredentialService.CredentialSoap)(this)).RequestSenderToken(inValue);
            return retVal.Body.RequestSenderTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsuranceCo.CredentialService.RequestCorrectTokenResponse InsuranceCo.CredentialService.CredentialSoap.RequestCorrectToken(InsuranceCo.CredentialService.RequestCorrectTokenRequest request) {
            return base.Channel.RequestCorrectToken(request);
        }
        
        public string RequestCorrectToken(string Email, string Password, string EnvelopeID, bool SuppressNavigation, string ReturnURL) {
            InsuranceCo.CredentialService.RequestCorrectTokenRequest inValue = new InsuranceCo.CredentialService.RequestCorrectTokenRequest();
            inValue.Body = new InsuranceCo.CredentialService.RequestCorrectTokenRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.EnvelopeID = EnvelopeID;
            inValue.Body.SuppressNavigation = SuppressNavigation;
            inValue.Body.ReturnURL = ReturnURL;
            InsuranceCo.CredentialService.RequestCorrectTokenResponse retVal = ((InsuranceCo.CredentialService.CredentialSoap)(this)).RequestCorrectToken(inValue);
            return retVal.Body.RequestCorrectTokenResult;
        }
    }
}
